carro/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "carro"

urlpatterns = [
    path("agregar/<int:producto_id>/", views.agregar_producto, name="agregar"),
    path("eliminar/<int:producto_id>/", views.eliminar_producto, name="eliminar"),
    path("restar/<int:producto_id>/", views.restar_producto, name="restar"),
    path("limpiar/", views.limpiar_carro, name="limpiar"),
]

distribuidora/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from core import views as core_views
from portfolio.urls import portfolio_patterns
from django.conf import settings

urlpatterns = [
    path("", core_views.home, name="home"),
    path("home/", core_views.inicio, name="home"),
    path("servicio/", core_views.servicio, name="servicio"),
    path("registrarse/", core_views.registrarse, name="registrarse"),
    path("logout/", core_views.exit, name="exit"),
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("portfolio/", include(portfolio_patterns)),
    path("carro/", include("carro.urls")),
    path("pedidos/", include("pedidos.urls")),
    path("autentication/", include("autentication.urls")),
]
if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.urls import path
from . import views
from .views import ProductoListView, ProductoDetailView, TipoListView
from django.conf import settings


portfolio_patterns = (
    [
        path("", TipoListView.as_view(), name="tipo"),
        path("tienda/", views.tienda, name="Tienda"),
        path("producto/", ProductoListView.as_view(), name="producto"),
        path(
            "productos/tipo/<str:tipo>/",
            ProductoListView.as_view(),
            name="productos_por_tipo",
        ),
    ],
    "portfolio",
)

portfolio/models.py
from django.db import models


class Tipo(models.Model):
    nombre_tipo = models.CharField(max_length=50, default="valor_predeterminado")
    image = models.ImageField(verbose_name="imagen", upload_to="projects")

    class Meta:
        verbose_name = "Tipo"
        verbose_name_plural = "Tipos"
        ordering = ["nombre_tipo"]

    def __str__(self):
        return self.nombre_tipo


class Marca(models.Model):
    nombre = models.CharField(max_length=200)
    nombre_proveedor = models.CharField(max_length=100, default="valor_predeterminado")

    class Meta:
        verbose_name = "Marca"
        verbose_name_plural = "Marcas"
        ordering = ["-nombre"]

    def __str__(self):
        return self.nombre


class Categoria(models.Model):
    nombre = models.CharField(max_length=50)
    tipo = models.ForeignKey(Tipo, on_delete=models.CASCADE, default=1)

    class Meta:
        verbose_name = "categoría"
        verbose_name_plural = "Categorías"
        ordering = ["nombre"]

    def __str__(self):
        return self.nombre


class Producto(models.Model):
    producto_id = models.CharField(max_length=10, unique=True, default=1)
    nombre = models.CharField(max_length=50)
    precio = models.FloatField()
    descripcion = models.TextField()
    nuevo = models.BooleanField()
    marca = models.ForeignKey(Marca, on_delete=models.PROTECT)
    tipo = models.ForeignKey(Tipo, on_delete=models.CASCADE, default=1)
    categoria = models.ForeignKey(
        Categoria, on_delete=models.CASCADE, default=1
    )  # Nueva relación con la tabla Categoria
    fecha_fabricacion = models.DateField()
    image = models.ImageField(verbose_name="imagen", upload_to="projects")
    create = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "producto"
        verbose_name_plural = "Articulos"
        ordering = ["-nombre"]

    def __str__(self):
        return self.nombre

portfolio/views.py
from django.shortcuts import render, get_object_or_404
from .models import Producto, Tipo
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView


# Create your views here.
def tienda(request):
    productos = Producto.objects.all()
    return render(request, "portfolio/producto_list.html", {"productos": productos})


class ProductoListView(ListView):
    model = Producto

    def get_queryset(self):
        tipo = self.kwargs.get("tipo")
        if tipo:
            return Producto.objects.filter(tipo__nombre_tipo=tipo)
        else:
            return Producto.objects.all()


class ProductoDetailView(DetailView):
    model = Producto


class TipoListView(ListView):
    model = Tipo

portfolio/templates/portfolio/categoria.html
{% extends 'core/base.html' %}
{% block contente %}
  {% load static %}
  {% include "portfolio/includes/productos_menu.html" %}
<div class="container_productos">
    <div class="contain_producto">
      {% for tipos in tipo_list %}
    <div class="card Todos">
        <img src="{{ tipos.image.url }}" class="card_img" alt="{{ tipos.nombre_tipo }}">
        <div>
            <h5>{{ tipos.nombre_tipo }}</h5>
        </div>
    </div>
    tipo: {{ tipos.nombre_tipo }}
{% endfor %}

    </div>
</div>
  {% endblock %}

portfolio/templates/portfolio/facturacion.html
{% extends 'core/base.html' %}
{% block title %}Facturación{% endblock %}

{% block contente %}
<div class="container">
    <h2>Facturación</h2>
    <form method="post" action="{% url 'facturar' %}">
        {% csrf_token %}
        <table class="table">
            <thead>
                <tr>
                    <th>Producto</th>
                    <th>Cantidad</th>
                </tr>
            </thead>
            <tbody>
                {% for item in carrito %}
                <tr>
                    <td>{{ item.producto.nombre }}</td>
                    <td>
                        <label for="cantidad_{{ item.producto.id }}">Cantidad:</label>
                        <input type="number" id="cantidad_{{ item.producto.id }}" name="cantidad_{{ item.producto.id }}" value="{{ item.cantidad }}" min="1">
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <button type="submit" class="btn btn-primary">Realizar Pago</button>
    </form>
</div>
{% endblock %}

portfolio/templates/portfolio/producto_detail.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}{{page.title}}{% endblock %}
{% block content %}
<main role="main">
  <div class="container">
    <div class="row mt-3">
      <div class="col-md-9 mx-auto">
        <h2 class="section-heading mb-4">{{producto.nombre}}</h2>
        <div>
          {{product.descripcion|safe}}
          
          {% if request.user.is_staff %}
          <p><a href="{% url 'pages:update' page.id %}">Editar</a></p>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

portfolio/templates/portfolio/producto_list.html
{% extends 'core/base.html' %}
{% block contente %}
  {% load static %}

  {% include "portfolio/includes/productos_menu.html" %}
<body class="body_producto">
  <div style="position: fixed; top: 5; right: 0; text-align: right;">
    <p style="color: black;"></p>
    {% include "carro/widget.html" %}
  </div>

  <div class="container_productos">
    <div class="contain_producto">
      {% for producto in producto_list %}
      <div class="card Todos">
        <img src="{{ producto.image.url }}" class="card_img" alt="{{ producto.nombre }}">
        <div >
          <h5 >{{ producto.nombre }}</h5>
          
          <p >Precio ={{ producto.precio|striptags|safe|truncatechars:"200" }}</p>
          
          <a href="{% url 'carro:agregar' producto.id %}" class="btn btn-primary">Agregar al Carro</a>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</body>


{% endblock %}

portfolio/templates/portfolio/tipo_list.html
{% extends 'core/base.html' %}
{% block contente %}
  {% load static %}
  {% include "portfolio/includes/productos_menu.html" %}
<div class="container_productos">
    
    <div class="contain_producto">
      {% for tipos in tipo_list %}
       <div class="card Todos">
            <img src="{{ tipos.image.url }}" class="card_img" alt="{{ tipos.nombre_tipo }}">
            <div >
                <h5 >{{ tipos.nombre_tipo }}</h5>
          
          
            </div>
        </div>
      {% endfor %}
    </div>
</div>
  {% endblock %}