carro/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "carro"

urlpatterns = [
    path("agregar/<int:producto_id>/", views.agregar_producto, name="agregar"),
    path("eliminar/<int:producto_id>/", views.eliminar_producto, name="eliminar"),
    path("restar/<int:producto_id>/", views.restar_producto, name="restar"),
    path("limpiar/", views.limpiar_carro, name="limpiar"),
]

distribuidora/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from core import views as core_views
from portfolio.urls import portfolio_patterns
from django.conf import settings

urlpatterns = [
    path("", core_views.home, name="home"),
    path("home/", core_views.inicio, name="home"),
    path("servicio/", core_views.servicio, name="servicio"),
    path("registrarse/", core_views.registrarse, name="registrarse"),
    path("logout/", core_views.exit, name="exit"),
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("portfolio/", include(portfolio_patterns)),
    path("carro/", include("carro.urls")),
    path("pedidos/", include("pedidos.urls")),
    path("autentication/", include("autentication.urls")),
]
if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pedidos/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "pedidos"

urlpatterns = [
    path("tienda/", views.Procesar_pedido, name="procesar_pedido"),
]

portfolio/urls.py
from django.urls import path
from . import views
from .views import ProductoListView, ProductoDetailView, TipoListView
from django.conf import settings


portfolio_patterns = (
    [
        path("", TipoListView.as_view(), name="tipo"),
        path("tienda/", views.tienda, name="Tienda"),
        path("producto/", ProductoListView.as_view(), name="producto"),
        path(
            "productos/tipo/<str:tipo>/",
            ProductoListView.as_view(),
            name="productos_por_tipo",
        ),
    ],
    "portfolio",
)

carro/models.py
from django.db import models

# Create your models here.

portfolio/models.py
from django.db import models


class Tipo(models.Model):
    nombre_tipo = models.CharField(max_length=50, default="valor_predeterminado")
    image = models.ImageField(verbose_name="imagen", upload_to="projects")

    class Meta:
        verbose_name = "Tipo"
        verbose_name_plural = "Tipos"
        ordering = ["nombre_tipo"]

    def __str__(self):
        return self.nombre_tipo


class Marca(models.Model):
    nombre = models.CharField(max_length=200)
    nombre_proveedor = models.CharField(max_length=100, default="valor_predeterminado")

    class Meta:
        verbose_name = "Marca"
        verbose_name_plural = "Marcas"
        ordering = ["-nombre"]

    def __str__(self):
        return self.nombre


class Categoria(models.Model):
    nombre = models.CharField(max_length=50)
    tipo = models.ForeignKey(Tipo, on_delete=models.CASCADE, default=1)

    class Meta:
        verbose_name = "categoría"
        verbose_name_plural = "Categorías"
        ordering = ["nombre"]

    def __str__(self):
        return self.nombre


class Producto(models.Model):
    producto_id = models.CharField(max_length=10, unique=True, default=1)
    nombre = models.CharField(max_length=50)
    precio = models.FloatField()
    descripcion = models.TextField()
    nuevo = models.BooleanField()
    marca = models.ForeignKey(Marca, on_delete=models.PROTECT)
    tipo = models.ForeignKey(Tipo, on_delete=models.CASCADE, default=1)
    categoria = models.ForeignKey(
        Categoria, on_delete=models.CASCADE, default=1
    )  # Nueva relación con la tabla Categoria
    fecha_fabricacion = models.DateField()
    image = models.ImageField(verbose_name="imagen", upload_to="projects")
    create = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "producto"
        verbose_name_plural = "Articulos"
        ordering = ["-nombre"]

    def __str__(self):
        return self.nombre

carro/views.py
from django.shortcuts import render
from .carro import Carro
from portfolio.models import Producto
from django.shortcuts import redirect


def agregar_producto(request, producto_id):
    carro = Carro(request)
    producto = Producto.objects.get(id=producto_id)
    carro.agregar(producto=producto)

    return redirect("portfolio:Tienda")


def eliminar_producto(request, producto_id):
    carro = Carro(request)
    producto = Producto.objects.get(id=producto_id)
    carro.eliminar(producto=producto)

    return redirect("producto")


def restar_producto(request, producto_id):
    carro = Carro(request)
    producto = Producto.objects.get(id=producto_id)
    carro.restar_producto(producto=producto)

    return redirect("portfolio:Tienda")


def limpiar_carro(request, producto_id):
    carro = Carro(request)
    carro.limpiar_carro()

    return redirect("producto")

portfolio/views.py
from django.shortcuts import render, get_object_or_404
from .models import Producto, Tipo
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView


# Create your views here.
def tienda(request):
    productos = Producto.objects.all()
    return render(request, "portfolio/producto_list.html", {"productos": productos})


class ProductoListView(ListView):
    model = Producto

    def get_queryset(self):
        tipo = self.kwargs.get("tipo")
        if tipo:
            return Producto.objects.filter(tipo__nombre_tipo=tipo)
        else:
            return Producto.objects.all()


class ProductoDetailView(DetailView):
    model = Producto


class TipoListView(ListView):
    model = Tipo

portfolio/templates/carro/widget.html
{% if  request.session %}
    <table class="table table-bordered" style="color" black>

        <thead>
            <tr>
                <th colspan ="3" class= "text-center">Carrito compras</th>
            </tr>
            <tr>
                <th >Producto</th>
                <th >Cantidad</th>
                <th >Suma</th>
            </tr>

        </thead>

        <tbody>
        {% if request.session.carro %}
            {% for key, value in request.session.carro.items %}
                <tr>
                    <td>{{ value.nombre }}</td>
                    <td>{{ value.cantidad }}</td>
                    <td>
                        <a href="{% url 'carro:agregar' value.producto_id %}" class="btn btn-sm btn-success">+</a>
                        <a href="{% url 'carro:restar' value.producto_id %}" class="btn btn-sm btn-success">-</a>
                        {{ value.precio }}
                    </td>
                </tr>
            
            {% endfor %}
        {% else %}
            <tr>
                <th colspan="3">
                    <div class="alert alert-danger text-center">
                     Sin Productos
                    </div>
                </th>
            </tr>
        {% endif %}
    </tbody>

        <tfoot>
            <tr>
                <td colspan = "3"> 
                    Total: ${{importe_total_carro}} 
                </td>
            </tr>
            {% if request.session.carro.items %}
                <tr> 
                    <td colspan = "3" style= "text-center">
                        <a href="{% url 'pedidos:procesar_pedido'%}" class= "btn btn-success">Hacer Pedido</a>
                </tr>
            {% endif %}
        </tfoot>



    </table>
{% endif %}